Description: "Create basic notebook instance"
Resources:
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName:  !Sub '${AWS::StackName}-notebook-instance' 
      InstanceType: "ml.t2.medium"
      RoleArn: !GetAtt ExecutionRole.Arn
  ExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName:  !Sub '${AWS::StackName}-notebook-role'
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
        - 
          Effect: "Allow"
          Principal: 
            Service: 
              - "sagemaker.amazonaws.com"
          Action: 
          - "sts:AssumeRole"
      Path: "/"
      Policies: 
        - 
          PolicyName: "sagemaker-notebook-policy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: 'arn:aws:s3:::*/*'
              - Effect: "Allow"
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                Resource: 'arn:aws:s3:::*'
              - Effect: "Allow"
                Action:                 
                  - "athena:CreateNamedQuery"
                  - "athena:GetQueryExecution"
                  - "athena:GetQueryResults"
                  - "athena:StartQueryExecution"
                Resource: !Sub 'arn:aws:athena:*:${AWS::AccountId}:workgroup/*'
              - Effect: "Allow"
                Action:
                  - "glue:CreateDatabase"
                  - "glue:CreateTable"
                  - "glue:GetDatabase"
                  - "glue:GetTable"
                Resource: [ !Sub 'arn:aws:glue:*:${AWS::AccountId}:database/*',
                            !Sub 'arn:aws:glue:*:${AWS::AccountId}:catalog',
                          !Sub 'arn:aws:glue:*:${AWS::AccountId}:table/*/*'
                          ]
              - Effect: "Allow"
                Action:
                  - "iam:PutUserPolicy"
                  - "iam:UpdateAccessKey"
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:user/*'                
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance
    Value: !GetAtt BasicNotebookInstance.NotebookInstanceName